
export const genesis1= [
  {
    _id: "62732463a09db64c94514851",
    originCharter: 'Genesis 1',
    numero: 1,
    versiculo: 'En el principio creó Dios los cielos y la tierra.',
    version: 'Reina_Valera_1960',
    userCreator: 'JerryBD',
    testament: 'Antiguo testamento',
    like: 0,
    view: 0,
    __v: 0,
    title: 'La creación'
  },
  {
    _id: "62732463a09db64c94514853",
    originCharter: 'Genesis 1',
    numero: 2,
    versiculo: 'Y la tierra estaba desordenada y vacía, y las tinieblas estaban sobre la faz del abismo, y el Espíritu de Dios se movía sobre la faz de las aguas.',
    version: 'Reina_Valera_1960',
    userCreator: 'JerryBD',
    testament: 'Antiguo testamento',
    like: 0,
    view: 0,
    __v: 0
  },
  {
    _id: "62732463a09db64c94514855",
    originCharter: 'Genesis 1',
    numero: 3,
    versiculo: 'Y dijo Dios: Sea la luz; y fue la luz.',
    version: 'Reina_Valera_1960',
    userCreator: 'JerryBD',
    testament: 'Antiguo testamento',
    like: 0,
    view: 0,
    __v: 0
  },
  {
    _id:"62732464a09db64c94514857",
    originCharter: 'Genesis 1',
    numero: 4,
    versiculo: 'Y vio Dios que la luz era buena; y separó Dios la luz de las tinieblas.',
    version: 'Reina_Valera_1960',
    userCreator: 'JerryBD',
    testament: 'Antiguo testamento',
    like: 0,
    view: 0,
    __v: 0
  },
  {
    _id: "62732464a09db64c94514859",
    originCharter: 'Genesis 1',
    numero: 5,
    versiculo: 'Y llamó Dios a la luz Día, y a las tinieblas llamó Noche. Y fue la tarde y la mañana un día.',
    version: 'Reina_Valera_1960',
    userCreator: 'JerryBD',
    testament: 'Antiguo testamento',
    like: 0,
    view: 0,
    __v: 0
  },
  {
    _id: "62732464a09db64c9451485b",
    originCharter: 'Genesis 1',
    numero: 6,
    versiculo: 'Luego dijo Dios: Haya expansión en medio de las aguas, y separe las aguas de las aguas.',
    version: 'Reina_Valera_1960',
    userCreator: 'JerryBD',
    testament: 'Antiguo testamento',
    like: 0,
    view: 0,
    __v: 0
  },
  {
    _id: "62732464a09db64c9451485d",
    originCharter: 'Genesis 1',
    numero: 7,
    versiculo: 'E hizo Dios la expansión, y separó las aguas que estaban debajo de la expansión, de las aguas que estaban sobre la expansión. Y fue así.',
    version: 'Reina_Valera_1960',
    userCreator: 'JerryBD',
    testament: 'Antiguo testamento',
    like: 0,
    view: 0,
    __v: 0
  },
  {
    _id: "62732464a09db64c9451485f",
    originCharter: 'Genesis 1',
    numero: 8,
    versiculo: 'Y llamó Dios a la expansión Cielos. Y fue la tarde y la mañana el día segundo.',       
    version: 'Reina_Valera_1960',
    userCreator: 'JerryBD',
    testament: 'Antiguo testamento',
    like: 0,
    view: 0,
    __v: 0
  },
  {
    _id: "62732464a09db64c94514861",
    originCharter: 'Genesis 1',
    numero: 9,
    versiculo: 'Dijo también Dios: Júntense las aguas que están debajo de los cielos en un lugar, y descúbrase lo seco. Y fue así.',
    version: 'Reina_Valera_1960',
    userCreator: 'JerryBD',
    testament: 'Antiguo testamento',
    like: 0,
    view: 0,
    __v: 0
  },
  {
    _id: "62732464a09db64c94514863",
    originCharter: 'Genesis 1',
    numero: 10,
    versiculo: 'Y llamó Dios a lo seco Tierra, y a la reunión de las aguas llamó Mares. Y vio Dios que era bueno.'
,
    version: 'Reina_Valera_1960',
    userCreator: 'JerryBD',
    testament: 'Antiguo testamento',
    like: 0,
    view: 0,
    __v: 0
  },
  {
    _id: "62732464a09db64c94514865",
    originCharter: 'Genesis 1',
    numero: 11,
    versiculo: 'Después dijo Dios: Produzca la tierra hierba verde, hierba que dé semilla; árbol de fruto que dé fruto según su género, que su semilla esté en él, sobre la tierra. Y fue así.',
    version: 'Reina_Valera_1960',
    userCreator: 'JerryBD',
    testament: 'Antiguo testamento',
    like: 0,
    view: 0,
    __v: 0
  },
  {
    _id: "62732464a09db64c94514867",
    originCharter: 'Genesis 1',
    numero: 12,
    versiculo: 'Produjo, pues, la tierra hierba verde, hierba que da semilla según su naturaleza, y árbol que da fruto, cuya semilla está en él, según su género. Y vio Dios que era bueno.',
    version: 'Reina_Valera_1960',
    userCreator: 'JerryBD',
    testament: 'Antiguo testamento',
    like: 0,
    view: 0,
    __v: 0
  },
  {
    _id: "62732465a09db64c94514869",
    originCharter: 'Genesis 1',
    numero: 13,
    versiculo: 'Y fue la tarde y la mañana el día tercero.',
    version: 'Reina_Valera_1960',
    userCreator: 'JerryBD',
    testament: 'Antiguo testamento',
    like: 0,
    view: 0,
    __v: 0
  },
  {
    _id: "62732465a09db64c9451486b",
    originCharter: 'Genesis 1',
    numero: 14,
    versiculo: 'Dijo luego Dios: Haya lumbreras en la expansión de los cielos para separar el día de la noche; y sirvan de señales para las estaciones, para días y años,',
    version: 'Reina_Valera_1960',
    userCreator: 'JerryBD',
    testament: 'Antiguo testamento',
    like: 0,
    view: 0,
    __v: 0
  },
  {
    _id: "62732465a09db64c9451486d",
    originCharter: 'Genesis 1',
    numero: 15,
    versiculo: 'y sean por lumbreras en la expansión de los cielos para alumbrar sobre la tierra. Y fue así.',
    version: 'Reina_Valera_1960',
    userCreator: 'JerryBD',
    testament: 'Antiguo testamento',
    like: 0,
    view: 0,
    __v: 0
  },
  {
    _id: "62732465a09db64c9451486f",
    originCharter: 'Genesis 1',
    numero: 16,
    versiculo: 'E hizo Dios las dos grandes lumbreras; la lumbrera mayor para que señorease en el día, y la lumbrera menor para que señorease en la noche; hizo también las estrellas.',

    version: 'Reina_Valera_1960',
    userCreator: 'JerryBD',
    testament: 'Antiguo testamento',
    like: 0,
    view: 0,
    __v: 0
  },
  {
    _id: "62732465a09db64c94514871",
    originCharter: 'Genesis 1',
    numero: 17,
    versiculo: 'Y las puso Dios en la expansión de los cielos para alumbrar sobre la tierra,',
    version: 'Reina_Valera_1960',
    userCreator: 'JerryBD',
    testament: 'Antiguo testamento',
    like: 0,
    view: 0,
    __v: 0
  },
  {
    _id: "62732465a09db64c94514873",
    originCharter: 'Genesis 1',
    numero: 18,
    versiculo: 'y para señorear en el día y en la noche, y para separar la luz de las tinieblas. Y vio Dios que era bueno.',

    version: 'Reina_Valera_1960',
    userCreator: 'JerryBD',
    testament: 'Antiguo testamento',
    like: 0,
    view: 0,
    __v: 0
  },
  {
    _id: "62732465a09db64c94514875",
    originCharter: 'Genesis 1',
    numero: 19,
    versiculo: 'Y fue la tarde y la mañana el día cuarto.',
    version: 'Reina_Valera_1960',
    userCreator: 'JerryBD',
    testament: 'Antiguo testamento',
    like: 0,
    view: 0,
    __v: 0
  },
  {
    _id: "62732465a09db64c94514877",
    originCharter: 'Genesis 1',
    numero: 20,
    versiculo: 'Dijo Dios: Produzcan las aguas seres vivientes, y aves que vuelen sobre la tierra, en la abierta expansión de los cielos.',
    version: 'Reina_Valera_1960',
    userCreator: 'JerryBD',
    testament: 'Antiguo testamento',
    like: 0,
    view: 0,
    __v: 0
  },
  {
    _id: "62732465a09db64c94514879",
    originCharter: 'Genesis 1',
    numero: 21,
    versiculo: 'Y creó Dios los grandes monstruos marinos, y todo ser viviente que se mueve, que las aguas produjeron según su género, y toda ave alada según su especie. Y vio Dios que era bueno.',
    version: 'Reina_Valera_1960',
    userCreator: 'JerryBD',
    testament: 'Antiguo testamento',
    like: 0,
    view: 0,
    __v: 0
  },
  {
    _id: "62732466a09db64c9451487b",
    originCharter: 'Genesis 1',
    numero: 22,
    versiculo: 'Y Dios los bendijo, diciendo: Fructificad y multiplicaos, y llenad las aguas en los mares, y multiplíquense las aves en la tierra.',
    version: 'Reina_Valera_1960',
    userCreator: 'JerryBD',
    testament: 'Antiguo testamento',
    like: 0,
    view: 0,
    __v: 0
  },
  {
    _id: "62732466a09db64c9451487d",
    originCharter: 'Genesis 1',
    numero: 23,
    versiculo: 'Y fue la tarde y la mañana el día quinto.',
    version: 'Reina_Valera_1960',
    userCreator: 'JerryBD',
    testament: 'Antiguo testamento',
    like: 0,
    view: 0,
    __v: 0
  },
  {
    _id: "62732466a09db64c9451487f",
    originCharter: 'Genesis 1',
    numero: 24,
    versiculo: 'Luego dijo Dios: Produzca la tierra seres vivientes según su género, bestias y serpientes y animales de la tierra según su especie. Y fue así.',
    version: 'Reina_Valera_1960',
    userCreator: 'JerryBD',
    testament: 'Antiguo testamento',
    like: 0,
    view: 0,
    __v: 0
  },
  {
    _id:"62732466a09db64c94514881",
    originCharter: 'Genesis 1',
    numero: 25,
    versiculo: 'E hizo Dios animales de la tierra según su género, y ganado según su género, y todo animal que se arrastra sobre la tierra según su especie. Y vio Dios que era bueno.',
    version: 'Reina_Valera_1960',
    userCreator: 'JerryBD',
    testament: 'Antiguo testamento',
    like: 0,
    view: 0,
    __v: 0
  },
  {
    _id: "62732466a09db64c94514883",
    originCharter: 'Genesis 1',
    numero: 26,
    versiculo: 'Entonces dijo Dios: Hagamos al hombre a nuestra imagen, conforme a nuestra semejanza; y señoree en los peces del mar, en las aves de los cielos, en las bestias, en toda la tierra, y en todo animal que se arrastra sobre la tierra.',
    version: 'Reina_Valera_1960',
    userCreator: 'JerryBD',
    testament: 'Antiguo testamento',
    like: 0,
    view: 0,
    __v: 0
  },
  {
    _id: "62732466a09db64c94514885",
    originCharter: 'Genesis 1',
    numero: 27,
    versiculo: 'Y creó Dios al hombre a su imagen, a imagen de Dios lo creó; varón y hembra los creó.',      version: 'Reina_Valera_1960',
    userCreator: 'JerryBD',
    testament: 'Antiguo testamento',
    like: 0,
    view: 0,
    __v: 0
  },
  {
    _id: "62732466a09db64c94514887",
    originCharter: 'Genesis 1',
    numero: 28,
    versiculo: 'Y los bendijo Dios, y les dijo: Fructificad y multiplicaos; llenad la tierra, y sojuzgadla, y señoread en los peces del mar, en las aves de los cielos, y en todas las bestias que se mueven sobre la tierra.',
    version: 'Reina_Valera_1960',
    userCreator: 'JerryBD',
    testament: 'Antiguo testamento',
    like: 0,
    view: 0,
    __v: 0
  },
  {
    _id: "62732466a09db64c94514889",
    originCharter: 'Genesis 1',
    numero: 29,
    versiculo: 'Y dijo Dios: He aquí que os he dado toda planta que da semilla, que está sobre toda la tierra, y todo árbol en que hay fruto y que da semilla; os serán para comer.',

    version: 'Reina_Valera_1960',
    userCreator: 'JerryBD',
    testament: 'Antiguo testamento',
    like: 0,
    view: 0,
    __v: 0
  },
  {
    _id: "62732466a09db64c9451488b",
    originCharter: 'Genesis 1',
    numero: 30,
    versiculo: 'Y a toda bestia de la tierra, y a todas las aves de los cielos, y a todo lo que se arrastra sobre la tierra, en que hay vida, toda planta verde les será para comer. Y fue así.',
    version: 'Reina_Valera_1960',
    userCreator: 'JerryBD',
    testament: 'Antiguo testamento',
    like: 0,
    view: 0,
    __v: 0
  },
  {
    _id: "62732467a09db64c9451488d",
    originCharter: 'Genesis 1',
    numero: 31,
    versiculo: 'Y vio Dios todo lo que había hecho, y he aquí que era bueno en gran manera. Y fue la tarde y la mañana el día sexto.',
    version: 'Reina_Valera_1960',
    userCreator: 'JerryBD',
    testament: 'Antiguo testamento',
    like: 0,
    view: 0,
    __v: 0
  }
  ]
  
